### ISSUE TITLE
Unable to tick multiple files for batch operation in PSP

### ISSUE THREAD

**Issue by kathyrollo** [joel16/CMFileManager-PSP#10]
## Summary
Checkboxes cannot be ticked for multiple file processing. Single file operation works.

## Screenshot
![pic_0000](https://user-images.githubusercontent.com/28589393/48464518-c3688200-e81a-11e8-8e12-e0ea15e739b0.png)

## Steps

1. Press Triangle on a file/folder (collectively, "item") to open Actions menu.
2. Select Move (or Copy) option. The current item is not ticked.
3. Press Triangle to close Actions menu on current item.
4. Choose another item, press Triangle.
5. Move has been replaced with Paste. Therefore, user cannot select Move for the additional item.

## Actual Result
Selected items are not ticked when actions are performed on them. Batch processing unavailable.

## Expected Result
Checkboxes indicate batch processing.

## Workaround
Copy/Move/Delete items individually.

## Possible Solution
- [ ] An item is ticked once Copy/Move/Delete is selected from the Actions menu whether single or multiple.
- [ ] Paste does not replace Copy/Move in the Actions menu but becomes an added option to allow batch processing. Single file operation can also work this way.
- [ ] For Delete, user can be asked to delete current selected item (single) OR continue adding items to delete (batch).
- [ ] Batch mode works for combinations of items (file + folder, file + file, folder + folder).
- [ ] Batch mode only shows Properties/Copy/Move/Delete.
- [ ] Properties only shows Size (computed total) when multiple files selected.
- [ ] Rename/New folder for single file operation only. Both options disappear from the Actions menu when in batch mode.

Probably a good candidate for V2 milestone.

## Environment
Model: PSP-3000 (TA-090v2, 03g)
LCFW: 6.60 PRO-C2

**Comment by joel16** [comment]
Not sure if I see the problem here. It allows you to select multiple files and folders in one directory, which you can then move/copy to another directory or simply delete. It works similar to how you hold the **CTRL** button on windows, which allows you to select multiple files and folder in a single directory, then you can do whatever you want with them. Also the only batch file processing functions are delete/move/copy, I don't really see why I need to not display the others just for this case. They simply won't work, and it's just putting more work on my table :P

**Comment by kathyrollo** [comment]
Heya @joel16 ,

Are you testing on Vita (touch) or the PSP? So far, I have not managed to do batch processing with the usual PSP-3000 buttons. Might you add additional documentation to the README?

**Comment by joel16** [comment]
Do you have discord or anything? Might be easier to talk there.
Also you press square to check/uncheck and then press triangle to use the options menu to batch move/copy/delete.
