### ISSUE TITLE
Icon not visible in PSP

### ISSUE THREAD

**Issue by kathyrollo** [joel16/CMFileManager-PSP#11]
## Summary
Pretty sure there is an ICON0.PNG and a merged PR for it, but the XMB is not picking it up.

## Screenshot
![pic_0000](https://user-images.githubusercontent.com/28589393/48466336-84d5c600-e820-11e8-94fc-b47277264a6f.png)

## Expected Result
![icon0](https://user-images.githubusercontent.com/28589393/48466411-c5cdda80-e820-11e8-8b58-91eec1ae2d7e.PNG)

## Environment
Model: PSP-3000 (TA-090v2, 03g)
LCFW: 6.60 PRO-C2

**Comment by joel16** [comment]
Works fine in my builds. The merged PR was after the initial release.

**Comment by kathyrollo** [comment]
Ah I see, need to wait for the next stable to get other fixes in.
