### ISSUE TITLE
Newbie guard for flash0 and flash1 in Settings

### ISSUE THREAD

**Issue by kathyrollo** [joel16/CMFileManager-PSP#12]
## Summary
flash0 and flash1 disabled by default (Select). Can be toggled in Settings (Start).

**Comment by joel16** [comment]
Apologize for being a year late, but I finally got around to implementing this rather simple feature. Fixed with https://github.com/joel16/CMFileManager-PSP/commit/cb168d1ca159f50c367aaa92f9daf7d87612258c.
