### ISSUE TITLE
List mode view + cursor stuck

### ISSUE THREAD

**Issue by RS55** [joel16/CMFileManager-PSP#14]
Well what the title says, a list mode option (since the width of the top bar I see something ... exaggerated? IMO) And on the other hand when go up the file list, the cursor is stuck in the last file (below) from the screen until reach the top.

For the rest, great work!

EDIT: I would like to suggest that the "Parent Folder" will become "...", most of the file explorers are like that and it would be better, but it is my opinion only.

**Comment by joel16** [comment]
Well it's replicating CyanogenMod file manager. So it's supposed to look like that: https://i.stack.imgur.com/rWCfl.png

I'm not sure if I want to implement other views, just more bulk in code that I'd like to avoid to be honest.

"Parent Folder" will become "..." -> I'm aware of this, but this is purely for design purposes to make it similar to the original CM File Manager, so this won't change.
