### ISSUE TITLE
Check if O or X is accept button and use it

### ISSUE THREAD

**Issue by YChvanov** [joel16/CMFileManager-PSP#15]
You can change it by recovery menu: "Registery hacks" -> "Swap O/X buttons .."
I use O because I usually play Asian games where no swapping supported (ex. DJMax series, anti-ex. LocoRoco 2)

**Comment by joel16** [comment]
https://github.com/joel16/CMFileManager-PSP/commit/4cdef7585868bf36cddbfa8726f7b77c65882309
