### ISSUE TITLE
Function to browse UMD-disc contains

### ISSUE THREAD

**Issue by YChvanov** [joel16/CMFileManager-PSP#16]
disk0:/ if I'm not making a mistake

**Comment by joel16** [comment]
I only have a PSP GO, so I won't be able to test anything. Can you test this eboot? https://drive.google.com/file/d/13cl5WJrK0SncmhCi08wg2qrMCZOAFpmC/view?usp=sharing

It should display something like:
```
.
PSP_GAME
```

**Comment by joel16** [comment]
Sorry forgot to initialize debug screen. Try this: (Won't work on PPSSPP btw) https://drive.google.com/open?id=1GWQm2WxTnqej5F2Eha8kiVBFOVr5QiB7

You should see something like:

```
UMD mounted
UMD can be accessed!
0 '.'
0 'PSP_GAME/'
0 'UMD_DATA.BIN'
```

**Comment by YChvanov** [comment]
It works

**Comment by joel16** [comment]
Ok thanks for testing! It will be available in the next release (should be by the end of this week or soon).

**Comment by joel16** [comment]
https://github.com/joel16/CMFileManager-PSP/commit/6c11676952d6d693883e62d36fb9012d87ff725c

**Comment by joel16** [comment]
Can you test this just to be sure? https://drive.google.com/open?id=1pNBB3UhhvEhXekCQMU7BsFo0TeqsnRBN

This is almost the full release that I will upload in a bit. I just want to make sure it's working. Thanks. (PS. You don't need the "data" folder anymore)

**Comment by YChvanov** [comment]
App freezes after selecting the item w/o UMD until you insert one

**Comment by joel16** [comment]
I'm assuming it works after? I can fix that.
