### ISSUE TITLE
Add some kind of readme file with version in app root

### ISSUE THREAD

**Issue by YChvanov** [joel16/CMFileManager-PSP#19]
So that you can check which version you have without launching application
It'd good if it'd generate with makefile ('echo "" > readme.txt' or something)

Example folder structure:
CMFileManager:\
+EBOOT.PBP
+readme.txt
+data:\
++*

**Comment by joel16** [comment]
I'm kind of against this. There's only one place where you should download this from, and it's GitHub which explicitly tells you which version it is. Sorry but I don't think this is necessary.
