### ISSUE TITLE
[FR] add ICON0.png

### ISSUE THREAD

**Issue by JesterIOS** [joel16/CMFileManager-PSP#2]
**ICON0.png**
![icon0](https://user-images.githubusercontent.com/30769120/47896978-6546b100-dea2-11e8-9616-1f609c7f7f43.png)

How it looks on PSP:
![pic_0000](https://user-images.githubusercontent.com/30769120/47897025-8f986e80-dea2-11e8-98c8-cda1ecbcae63.png)

**Comment by joel16** [comment]
Is it not possible to use transparency? Also I'd prefer if this was used: https://github.com/LineageOS/android_packages_apps_CMFileManager/blob/cm-14.1/res/mipmap-xhdpi/ic_launcher_filemanager.png

**Comment by joel16** [comment]
Hmm would it be possible for it not be stretched out like that? You could just put the image in the center :P

**Comment by JesterIOS** [comment]
Well, if use a regular icon. then the appearance will be "slightly ugly".
Thats why i prefer use a wide icons on psp.

![image](https://user-images.githubusercontent.com/30769120/47955378-07ad8400-dfca-11e8-80ad-ac96abd11835.png)

**Comment by joel16** [comment]
Oh okay, well I guess this should be fine: 
![image](https://user-images.githubusercontent.com/30769120/47949339-cee2c000-df73-11e8-9b1c-5274c2c4a268.png)

Please make a PR, thanks!

**Comment by JesterIOS** [comment]
Done! =)
And now, I just have to close this issue.
