### ISSUE TITLE
The game could not be started (80010002)

### ISSUE THREAD

**Issue by YChvanov** [joel16/CMFileManager-PSP#22]
This happens because my homebrews are stored not in /PSP/GAME/ but in /PSP/GAME/%foldername%/, as I use [Game Categories Lite](https://github.com/codestation/gclite.git)

You should change the way app folder is being found, not just hard-code it: launcher/source/main.c - lines 12 and 13

Temporary workaround: place the app into /PSP/GAME/, but something

**Comment by joel16** [comment]
Can you try with this launcher? https://drive.google.com/open?id=1pNBB3UhhvEhXekCQMU7BsFo0TeqsnRBN

Replace the eboot.pbp with the one above^. Make sure the app.pbp is in the same folder.

**Comment by YChvanov** [comment]
👌

**Comment by joel16** [comment]
Fixed and reuploaded with https://github.com/joel16/CMFileManager-PSP/commit/67eda768a56a667930ce10e4f72796b3d6ec8df6
