### ISSUE TITLE
Battery percentage wrong when no battery inserted

### ISSUE THREAD

**Issue by Brawl345** [joel16/CMFileManager-PSP#26]
When no battery is inserted the battery percentage in the top right shows a wrong value. Running on a PSP 3000 on LME CFW 6.61 Infinity.

![pic_0001](https://user-images.githubusercontent.com/5049892/67163114-5e42d800-f36b-11e9-9f46-5a9319226a03.png)

**Comment by joel16** [comment]
Could you try this build? https://github.com/joel16/CMFileManager-PSP/raw/gh-pages/CMFileManager-PSP.zip

It should just display "0" if no battery is found (basically when scePowerGetBatteryLifePercent() fails)

**Comment by Brawl345** [comment]
Works!

![pic_0000](https://user-images.githubusercontent.com/5049892/67231740-37a2a100-f440-11e9-8aad-57864a2b3b69.png)

**Comment by joel16** [comment]
Thanks for confirming!
