### ISSUE TITLE
[Request] Add homebrew sorter function

### ISSUE THREAD

**Issue by MXPHunter** [joel16/CMFileManager-PSP#28]

**Comment by andrebrait** [comment]
This would definitely be nice, specially if it supports Categories Light plugin (which shouldn't be that hard).

This pretty much means being able to changes a file's (in case os ISOs) and folder's (in case of eboots) modification (or creation?) timestamps, IIRC

**Comment by joel16** [comment]
There's already a homebrew that does this I believe. This isn't really the purpose of a file manager IMO.

**Comment by MXPHunter** [comment]
There is only one and this one works wierd on latest fw
