### ISSUE TITLE
App crashes on Launch (PSP Go)

### ISSUE THREAD

**Issue by MarioKartFan** [joel16/CMFileManager-PSP#36]
Hi: 

I love this utility on the 3DS.  On my PSP however, it crashes upon launch.  The entire system shuts down.  I'm running a PSP Go with no Internal Memory Card (using Infinity 2.0 and latest Firmware).  I am working from a  clean install.

**Comment by joel16** [comment]
Damn, there is a problem with the launcher that launches the application with privileges to access both internal and external storage. I will release a new version in the coming days.

**Comment by joel16** [comment]
Actually the latest release runs fine on my Go. You said you're using with no internal memory card? I'm not sure if you worded that wrong but did you mean you're not using this on internal storage but rather external?

**Comment by joel16** [comment]
Can confirm latest release is working on PSP-Go, because that's the only PSP I own.
