### ISSUE TITLE
Ftp not functioning

### ISSUE THREAD

**Issue by DanHolli123** [joel16/CMFileManager-PSP#38]
On multiple networks when attempting to connect over ftp nothing shows

**Comment by DanHolli123** [comment]
*correction didn't realize that I'd have to manually search. 

Are the drives planned on being listed at some point or are they going to only be searchable?

**Comment by joel16** [comment]
The FTP is a port from libftpvita, it's already programmed to list the drives but it doesn't work and I'm not sure why.
