### ISSUE TITLE
[Request] Add SMB2/3 support

### ISSUE THREAD

**Issue by sahlberg** [joel16/CMFileManager-PSP#41]
With SMB2/3 client support it would be possible to copy files between the PSP and a windows/samba/azure/... share much easier than clunky FTP.

https://github.com/sahlberg/libsmb2
is a very small footprint, high performance, smb2/3 client that I maintain. It builds on virtually any platform that has bsd socket support, even tiny micro-controllers such as ESP32.

I think it would be awesome to have a filemanager on the PSP that could copy files between internal storage and a windows share.  If you want to do this, I will provide all the help I can from the libsmb2 side to make sure things work out.

(libsmb2 is the smb2/3 client used by kodi, vlc and many other projects. It is highly portable and allows them to ship smb2/3 support on all platforms they build for.)

**Comment by CDScissor** [comment]
Nothin' like random peeps makin' you update a program you thought was finalized. I'm all for this. I don't know if we should phase out FTP or have them both as options. It's up to the dev to decide on that one.

**Comment by joel16** [comment]
I don't know about this one, FTP was a bare minimum for me cause I felt like it was necessary for some sort of wireless file transfer. These days networking on a PSP is a pain since it doesn't support the most recent WiFi security protocols.

**Comment by CDScissor** [comment]
Fair point. I never really understood why Sony didn't update that even when the PSP was still alive. Perhaps they didn't think it was worth the effort or is it because of hardware restrictions rather than software. Can someone confirm this?
