### ISSUE TITLE
Improve Support docu

### ISSUE THREAD

**Issue by kathyrollo** [joel16/CMFileManager-PSP#42]
![screenshot_20201122-0](https://user-images.githubusercontent.com/28589393/99895968-6395f300-2ce0-11eb-82be-c20bb039b1b4.png)

To keep it up to date with the recent changes and show more info:

DPAD Up/Down: Cursor up/down
DPAD Left/Right: Start/end of listing
O or X: Enter/cancel (depends on region)
Triangle: File options
Start: Open settings
Select: Open side menu
L + R: Screenshot
Select + Start: Exit

**Comment by joel16** [comment]
I feel like controls are straight forward to the point where I've scrapped this dialog completely.
