### ISSUE TITLE
Screenshots save in PSP/PHOTO in PSP3000

### ISSUE THREAD

**Issue by kathyrollo** [joel16/CMFileManager-PSP#43]
Before:

![before](https://user-images.githubusercontent.com/28589393/99896024-de5f0e00-2ce0-11eb-8fc6-7576421d3f66.png)

Actual:

![now](https://user-images.githubusercontent.com/28589393/99895995-9d66f980-2ce0-11eb-88c0-f620ed49a7ec.png)

- Creates 2 folders: PSP/PHOTO and PSP/SCREENSHOT
- I remember it used to save in ms0:/PSP/SCREENSHOT instead?
- PNG is more efficient for storage space (a preference)

**Comment by joel16** [comment]
Two folders are no longer going to be created. It will strictly use the following format: ms0:/PSP/PHOTO/CMFileManager/screenshot_yyyymmdd-hhmmss.png

Also BMP is gone, and it writes a PNG using libpng instead. https://github.com/joel16/CMFileManager-PSP/commit/24066f7c4558930549ecdeeaae23ddbd691fe6c3
