### ISSUE TITLE
CMFILEMANAGER CRASHING AND FILES NOT SHOWING

### ISSUE THREAD

**Issue by thaynos** [joel16/CMFileManager-PSP#44]
i jsut installed this plugin on my psp it worked fine for the first minute but suddenly it just got stuck and i had to restart the psp. i dont remember what folder i was in when it crashed. when i tried to open it again it showed corrupted data. i plugged in my psp to the pc and when to the cmfilemanager directory in my GAME folder, and i saw that there was nothing inside of the filemanager folder. there was a debug.txt but it was empty. so i reinstalled the app using a fresh copy of the folder. but when i got into the app this time some of my song folders were missing. they were there before.

**Comment by joel16** [comment]
Sounds like you have a faulty sd card. Especially "when i tried to open it again it showed corrupted data." You may want to either try with a new card or backup everything and format your memory card.

**Comment by thaynos** [comment]
i mean the sdcard and adapter are both a week old only and i dint have any
problem with corruption until i opened the cmfilemanager app

>

**Comment by joel16** [comment]
Opening a folder shouldn't corrupt anything though.. it's not like it's writing anything to that folder like you mentioned.

**Comment by thaynos** [comment]
idk why then sorry

**Comment by joel16** [comment]
I would advise trying the new release with a new sd card.
