### ISSUE TITLE
PSP Go

### ISSUE THREAD

**Issue by GuyIncendiary** [joel16/CMFileManager-PSP#45]
App crashes on PSP Go, am i supposed to rename app.pbp to eboot then delete original eboot??

**Comment by GuyIncendiary** [comment]
I renamed it and it worked, u should consider adding this to the readme!

**Comment by joel16** [comment]
Oh yeah about this, the PSP GO version was meant only for PSP Go's who also have an external (m2) sd card. I didn't realize it wouldn't work if a user does not have an m2 SD card. I'll make sure to be clearer with that for the next and current release.
