### ISSUE TITLE
No quit dialog sometimes

### ISSUE THREAD

**Issue by Megas97** [joel16/CMFileManager-PSP#46]
Hello,

First of all I'd like to thank you for such a compete and amazing file manager for our beloved PSP :)
I'd like to report a bug which happens what seems like randomly. When I press the Home/PS button while in the file manager no dialog shows up and there's no way to quit it other than restarting my console via the power switch.
I can't seem to notice a pattern as to what could cause it but it's happened twice for a week now.
Would be thankful if you give your input on this.

**Comment by joel16** [comment]
Hi, I have decided to scrap the inbuilt home(exit) menu for this application. The next release will not have this issue as it will instead use the official PSP home menu.

**Comment by Megas97** [comment]
Yeah I noticed it had a custom one. OK, good to know. Thanks

**Comment by joel16** [comment]
Closed with https://github.com/joel16/CMFileManager-PSP/commit/2186d47dc82f4bea718132a419e465fbe6e876a4 as discussed earlier. (Wait for release or use artifacts from GitHub Actions)
