### ISSUE TITLE
Ability to open .conf files

### ISSUE THREAD

**Issue by Megas97** [joel16/CMFileManager-PSP#47]
Would it be possible in the next release to include the ability to open .conf files as text from inside the file manager? Right now .txt files work great and .ini open as well though some characters in them don't show up correctly so I'm afraid to edit and save them not to mess up the encoding. Would be nice to be able to edit .conf and .ini (not sure if it's ok now)  files directly on the psp as many programs use them for settings.

**Comment by joel16** [comment]
Sorry for being late but added support for .conf with https://github.com/joel16/CMFileManager-PSP/commit/63840f5bc1160962a212c7e35364b83710ec5924. You can either wait for an official release or grab a build artifact from here: https://github.com/joel16/CMFileManager-PSP/actions
