### ISSUE TITLE
cant access audio player on 4.01

### ISSUE THREAD

**Issue by ratboy777** [joel16/CMFileManager-PSP#48]
audio player works fine on 3.30 but not on 4.01. running on psp 3000 cfw infinity 6.61.

**Comment by joel16** [comment]
Its not enabled in 4.XX because its a re-write. Hopefully in next release if I get to it.

**Comment by ratboy777** [comment]
Sorry I didn't realize. looking forward to the next release as I like my music encoded in opus and this is the only way I've found to play it on PSP.

**Comment by joel16** [comment]
Just an FYI, this is back in [v4.10](https://github.com/joel16/CMFileManager-PSP/releases/tag/v4.10) :)
