### ISSUE TITLE
Feature request - Create/edit *.txt files

### ISSUE THREAD

**Issue by Darthagnon** [joel16/CMFileManager-PSP#5]
Thank you so much for making this homebrew - I've wished for a good file manager for years, but have had to stick to Genesis comp's PSP Claw Explorer or PSP Filer. Many times, I have wished to simply edit GAME.txt or create/edit a new config for some plugin (e.g. Pro Online). I was wondering, would it be possible to add the ability to create/edit *.txt files withing CMFileManager be an option in some future release?

**Comment by joel16** [comment]
Yeah I may look into this when I get more time. The code base is similar to the 3DS/Switch variants so once those get them, the PSP variant should follow too.

**Comment by joel16** [comment]
The most recent version has this feature.
