### ISSUE TITLE
Browse UMD

### ISSUE THREAD

**Issue by eubrunosilva** [joel16/CMFileManager-PSP#50]
Hi

I have a PSP 1001 with CFW 6.61 PRO-C

I'm trying to browser the UMD Files (tried with a game and an UMD Music)

If I press Select, I only have the ms0:/
If I connect thru FTP I dont have the UMD folder

Maybe I need to configure something else (I just copy the files/folder to the right place)

Thanks

**Comment by joel16** [comment]
You need to go to settings and enable "Developer options". This will display flash0-3 and UMD.

**Comment by eubrunosilva** [comment]
Hi
after enabling "Developer options" I got those options.

If I browse a Game its all ok.
If I try to browse an UMD Music/Video the software hangs. 

UMD Music/Video is not supported by software?
Thanks

**Comment by joel16** [comment]
Unfortunately I do not own a UMD video/music so I have not tested this with that. However games do work fine yes.

**Comment by eubrunosilva** [comment]
its possible to you to buy an umd video/music? many at low prices (i can pay that in advance to help you check this issue)
Thanks

**Comment by joel16** [comment]
Sorry I'm not really willing to do that at the moment.

**Comment by eubrunosilva** [comment]
ok. no problem.
thanks anyway
