### ISSUE TITLE
[3000] Copy/move/rename corrupting Memory Stick, crashing console, doing nothing, etc.

### ISSUE THREAD

**Issue by ParzivalWolfram** [joel16/CMFileManager-PSP#54]
I'm using CM v4.10 on a PSP 3000 running 6.60 LM. When trying to copy or move or rename files, most of the time, the file manager will either lock up or crash the PSP, or corrupt the Memory Stick. If these don't happen, the PSP shows activity on the Memory Stick, but nothing actually changes, so the copy/move/rename operations are more or less useless.

**Comment by joel16** [comment]
The problem is your pro duo adapter/SD card. I've tested this many times on a PSP 2000 and GO with internal storage and never encountered any such issues. 
FYI I also used LME on GO, ME on PSP 2K.
