### ISSUE TITLE
Feature request - Reorder XMB games mode?

### ISSUE THREAD

**Issue by Darthagnon** [joel16/CMFileManager-PSP#6]
PSP Filer has a mode to reorder games in the XMB, though it doesn't usually work very well. It display a list of ISO/CSO/etc and EBOOT games with their thumbnail art, and the user can move them up and down in the list - they *should* appear in this modified order on the XMB, though, in practice, this is a little glitchy. It is more reliable to edit the "file created" date or somesuch, and, as the XMB always displays the most recently added first, the order can be changed thusly.

I was wondering if a similar feature could be added to the roadmap, wherein, on a game-containing folder (for Categories Lite support) the user can enter reorder mode, in which game thumbnails are displayed, sorted by "most recent". The user can then select and move ISOs or whole EBOOT folders by selecting their icons and dropping them at the desired place in the list - this changes the date of the items relative to the items before and after them in the list, reordering the games upon return to the XMB. 

This is a feature that is lacking from the XMB and poorly implemented in PSP Filer, but that is incredibly useful, as one can then put your favourite games first, and that demo you just wanted to try a bit further down in the list.

Just an idea; forgive me if it is undesired/annoying. Thank you for your hard work so far on this project, and for CyanogenMod PSP :) 

Live long and prosper!

Darth Agnon
Monster Hunter, Planeswalker and Sith

**Comment by joel16** [comment]
Hey, thanks for the suggestion, but sorry this isn't trying to replicate any of PSPFiler's features. It's more about having a working open source user friendly file manager using up-to-date tools than implementing PSPFiler features. I'm sorry but I won't be working on this feature.
