### ISSUE TITLE
Unable to select CANCEL in Actions

### ISSUE THREAD

**Issue by kathyrollo** [joel16/CMFileManager-PSP#8]
**Description:**
Cannot navigate to CANCEL using D-buttons in Actions menu. In the confirmation dialogs, D-buttons can be used to select Yes/No.

**Screenshot:**
![actions_menu](https://user-images.githubusercontent.com/28589393/48440692-8b365480-e7c4-11e8-8751-442bc68d7fff.jpg)

**Workaround:**
Press Triangle again to exit Actions menu.

**Environment:**
Model: PSP-3000 (TA-090v2, 03g)
LCFW: 6.60 PRO-C2

**Comment by joel16** [comment]
Oh right, the cancel should be navigated using 'touch' but the PSP doesn't have touchscreen. Press triangle basically opens/closes it. I may just remove the CANCEL button.

**Comment by kathyrollo** [comment]
Sounds good!

**Comment by joel16** [comment]
Fixed with https://github.com/joel16/CMFileManager-PSP/commit/5e9cb29370236d7874987579e1252784a39f057c
