### ISSUE TITLE
Screenshots not displaying in Photo menu

### ISSUE THREAD

**Issue by kathyrollo** [joel16/CMFileManager-PSP#9]
**Description:**
Captured screenshots within the file manager do not display in Photo viewer.

**Screenshot:**
![pic_0001](https://user-images.githubusercontent.com/28589393/48442140-457b8b00-e7c8-11e8-8e68-72165b7e34b6.png)

**Steps:**

1. L+R to capture screen.
2. Screenshots saved to ms0:/PSP/SCREENSHOT/ directory (see above).
3. Select+Start to exit file manager.
4. Go to Photo in XMB.

**Actual Result:**
Screenshots not visible in Photo viewer.

**Expected Result:**
Screenshots visible in Photo viewer.

**Environment:**
Model: PSP-3000 (TA-090v2, 03g)
LCFW: 6.60 PRO-C2

**Comment by joel16** [comment]
Fixed with https://github.com/joel16/CMFileManager-PSP/commit/2be41590a7a54b1b2b9b385aa9a8d2207ad7d3f2
